import { z } from 'zod';

const port = z.number().int().min(1).max(65535);
const nonNegativeInt = z.number().int().min(0);
const absolutePath = z.string().regex(/^\//, 'pages.settings.validation.pathLeadingSlash');

export const AllSettingSchema = z.object({
  webListen: z.string().optional(),
  webDomain: z.string().optional(),
  webPort: port.optional(),
  webCertFile: z.string().optional(),
  webKeyFile: z.string().optional(),
  webBasePath: absolutePath.optional(),
  sessionMaxAge: z.number().int().min(1).max(525600).optional(),
  trustedProxyCIDRs: z.string().optional(),
  panelOutbound: z.string().optional(),
  pageSize: z.number().int().min(0).max(1000).optional(),
  expireDiff: nonNegativeInt.optional(),
  trafficDiff: nonNegativeInt.max(100).optional(),
  datepicker: z.enum(['gregorian', 'jalalian']).optional(),
  twoFactorEnable: z.boolean().optional(),
  twoFactorToken: z.string().optional(),
  xrayTemplateConfig: z.string().optional(),
  externalTrafficInformEnable: z.boolean().optional(),
  externalTrafficInformURI: z.string().optional(),
  restartXrayOnClientDisable: z.boolean().optional(),
  timeLocation: z.string().optional(),
  ldapEnable: z.boolean().optional(),
  ldapHost: z.string().optional(),
  ldapPort: port.optional(),
  ldapUseTLS: z.boolean().optional(),
  ldapInsecureSkipVerify: z.boolean().optional(),
  ldapBindDN: z.string().optional(),
  ldapPassword: z.string().optional(),
  ldapBaseDN: z.string().optional(),
  ldapUserFilter: z.string().optional(),
  ldapUserAttr: z.string().optional(),
  ldapVlessField: z.string().optional(),
  ldapSyncCron: z.string().optional(),
  ldapFlagField: z.string().optional(),
  ldapTruthyValues: z.string().optional(),
  ldapInvertFlag: z.boolean().optional(),
  ldapInboundTags: z.string().optional(),
  ldapAutoCreate: z.boolean().optional(),
  ldapAutoDelete: z.boolean().optional(),
  ldapDefaultTotalGB: nonNegativeInt.optional(),
  ldapDefaultExpiryDays: nonNegativeInt.optional(),
  ldapDefaultLimitIP: nonNegativeInt.optional(),
  hasTwoFactorToken: z.boolean().optional(),
  hasLdapPassword: z.boolean().optional(),
  hasApiToken: z.boolean().optional(),
  hasWarpSecret: z.boolean().optional(),
  hasNordSecret: z.boolean().optional(),
}).loose();

export type AllSettingInput = z.infer<typeof AllSettingSchema>;
